Revert 99 #81 saved list
ita-social-projects/Forum pull request #111
Opened 2023-08-17 19:27 UTC by Krymets

Fixed CompanySavedList

2023-08-17 19:59 UTC, Shushunya requested changes

2023-08-17 19:59 UTC, Shushunya commented on profiles/serializers.py
> +class CompanySavedListSerializer(serializers.ModelSerializer):
Do we need all of this fields her?

2023-08-17 19:59 UTC, Shushunya commented on profiles/views.py
> +    """
Redundant new line

2023-08-17 19:59 UTC, Shushunya commented on profiles/views.py
> +    def get(self, request):
```suggestion
    def list(self, request):
```

Change name so it triggers on GET request.

2023-08-17 19:59 UTC, Shushunya commented on profiles/views.py
Change method names so they are triggered when the request comes.
Add queryset, serializer_class and permission_classes attributes to SavedCompanyList. and SavedCompanyDetail. 
Documentaion: https://www.django-rest-framework.org/api-guide/generic-views/

2023-08-17 19:59 UTC, Shushunya commented on profiles/views.py
> +    def delete(self, request, pk):
```suggestion
    def destroy(self, request, pk):
```

Rename the method.

2023-08-17 19:59 UTC, Shushunya commented on profiles/views.py
> +        try:
This try-except block can be replaced with `get_object_or_404`

2023-08-17 19:59 UTC, Shushunya commented on profiles/views.py
> +        if SavedCompany.objects.filter(user=user, company_id=pk).exists():
get_object_or_404 Will do that manual check for you.

2023-08-17 21:02 UTC, Shushunya requested changes

2023-08-17 21:02 UTC, Shushunya commented on profiles/views.py
I've tried to run your branch locally but I constantly get 500 status.

2023-08-18 07:31 UTC, Krymets commented on profiles/views.py
> I've tried to run your branch locally but I constantly get 500 status.
Because you are not logged in and you are not passing the token in the request

2023-08-18 07:40 UTC, Krymets commented on profiles/views.py
> I've tried to run your branch locally but I constantly get 500 status.

![token](https://github.com/ita-social-projects/Forum/assets/51824412/bae75047-7a7a-4e5c-9c02-a4ed270fd9a8)

2023-08-18 07:48 UTC, Shushunya commented on profiles/views.py
Unfortunately no, that's not the problem. If I wasn't authorized, it should have been a 401 or 404 status but I have 500.

2023-08-18 08:00 UTC, Krymets commented on profiles/views.py
permission_classes = [IsAuthenticated] added, will now be correct

2023-08-18 11:25 UTC, Shushunya requested changes

2023-08-18 11:46 UTC, Krymets commented on profiles/views.py
> +    def get(self, request):
> Why you chose to override `get` not `list` method?

renamed

2023-08-18 11:46 UTC, Krymets commented on profiles/views.py
> +    def delete(self, request, pk):
> Why you chose to override delete, not `destroy` ?

renamed

2023-08-18 12:12 UTC, VovaD199 approved these changes

2023-08-18 12:12 UTC, Lvyshnevska approved these changes

2023-08-18 12:26 UTC, merged