#70reoganize frontend folder
ita-social-projects/Forum pull request #72
Opened 2023-08-10 08:03 UTC by BelousSofiya

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-08-10 14:32 UTC, Shushunya approved these changes

2023-08-13 19:33 UTC, Shushunya requested changes
My latest merge reorganized my files (SignUp Page folder). Consider it.

2023-08-13 20:15 UTC, Shushunya approved these changes

2023-08-14 11:18 UTC, mehalyna approved these changes

2023-08-14 11:18 UTC, merged